const express = require("express")
const cors = require("cors")
const connection = require("./connection")
const userRoutes = require("./routes/user")
const categoryRouter = require("./routes/category")
const productRoutes = require("./routes/product")
const billRoutes = require("./routes/bill")
const app = express()
app.use(cors())
app.use(express.urlencoded({extended:true}))
app.use(express.json())
// importing routes
app.use("/user",userRoutes)
app.use("/category",categoryRouter)
app.use("/product",productRoutes)
app.use("/bill",billRoutes)
module.exports = app